---
theme:
  name: material
  features:
    - navigation.sections
    - navigation.path
    - navigation.indexes
    - search.suggest
    - search.highlight
  palette:
    - scheme: default
      primary: white
      accent: amber
      toggle:
        icon: material/eye
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: amber
      toggle:
        icon: material/eye-outline
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
  font:
    text: Fira Sans
site_name: probdiffeq documentation
site_description: The documentation for the probdiffeq library.
site_author: Nicholas Krämer
strict: true
repo_url: https://github.com/pnkraemer/probdiffeq
repo_name: pnkraemer/probdiffeq

# Credit for a good amount of this setup: https://github.com/patrick-kidger/diffrax
extra_css: [_stylesheets/extra.css]
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.snippets:
      base_path: docs
  - admonition
  - toc:
      permalink: ¤
      toc_depth: 2
extra_javascript:
  # Credit:
  #  https://github.com/patrick-kidger/diffrax
  #  and https://squidfunk.github.io/mkdocs-material/reference/mathjax/
  - _javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
            show_signature_annotations: true
            show_bases: false
            show_source: false
            inherited_members: false
            show_if_no_docstring: true
            show_root_heading: false
            show_root_toc_entry: false
            merge_init_into_class: true
            members_order: alphabetical
            group_by_category: false
  - mkdocs-jupyter:
      include: ['*.py']
      execute: false
      allow_errors: false
  - awesome-pages
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/@pnkraemer
      name: pnkraemer
  generator: false
